version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  initdb:
    image: apache/airflow:2.9.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "airflow db init &&
               airflow users create --username airflow --password airflow --firstname Airflow --lastname User --role Admin --email airflow@example.com"

  webserver:
    image: apache/airflow:2.9.0
    restart: always
    depends_on:
      - postgres
      - initdb
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=jsDPRErfWFfJL2PvTkhuN2ZpQHsOVIruQDuJazJZM0U=
      - AIRFLOW__WEBSERVER__SECRET_KEY=long_and_random_secret_key
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/keyairflow.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./file_storage:/file_storage
      - ./credentials:/opt/airflow/credentials
    ports:
      - "8090:8080"
    command: webserver

  scheduler:
    image: apache/airflow:2.9.0
    restart: always
    depends_on:
      - postgres
      - initdb
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=jsDPRErfWFfJL2PvTkhuN2ZpQHsOVIruQDuJazJZM0U=
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/keyairflow.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./file_storage:/file_storage
      - ./credentials:/opt/airflow/credentials
    command: scheduler
